# Generated by Django 4.2.1 on 2023-05-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=30, unique=True, verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('operating_system', models.CharField(verbose_name='Операционная система')),
                ('release_year', models.DateField(verbose_name='Год релиза')),
                ('memory', models.IntegerField(choices=[(64, 'Small'), (128, 'Medium'), (256, 'Big')], verbose_name='Память')),
            ],
        ),
    ]
