# Generated by Django 4.2.1 on 2023-05-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='operating_system',
            field=models.CharField(choices=[(1, 'IOS'), (2, 'Android')], verbose_name='Операционная система'),
        ),
    ]
