# Generated by Django 4.2.1 on 2023-05-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_phone_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='memory',
            field=models.IntegerField(choices=[(1, 64), (2, 128), (3, 256)], verbose_name='Память'),
        ),
    ]
