# Generated by Django 4.2.1 on 2023-05-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_alter_phone_memory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Phone', 'verbose_name_plural': 'Phones'},
        ),
    ]
