# Generated by Django 4.2.1 on 2023-05-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0008_alter_phone_operating_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='operating_system',
            field=models.CharField(choices=[('IOS', 'IOS'), ('Android', 'Android')], verbose_name='Операционная система'),
        ),
    ]
