# Generated by Django 4.2.1 on 2023-05-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0011_alter_phone_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='memory',
            field=models.IntegerField(choices=[(64, 64), (128, 128), (256, 256)], verbose_name='Память'),
        ),
    ]
