# Generated by Django 4.2.1 on 2023-05-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0013_phone_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='delivery',
            field=models.IntegerField(default=0, verbose_name='Доставка'),
        ),
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
    ]
