# Generated by Django 4.2.1 on 2023-05-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0014_phone_delivery_phone_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='is_out_of_stocks',
            field=models.BooleanField(default=True, verbose_name='Есть ли в наличии'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
