# Generated by Django 4.2.1 on 2023-05-31 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phones', '0015_phone_is_out_of_stocks_alter_phone_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_system', models.CharField(choices=[('IOS', 'IOS'), ('Windows', 'Windows'), ('Linux', 'Linux')], verbose_name='Операционная система')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('release_year', models.DateField(verbose_name='Год релиза')),
                ('memory', models.IntegerField(choices=[(256, 256), (512, 512), (1024, 1024)], verbose_name='Память')),
                ('color', models.CharField(default='Grey', max_length=50, verbose_name='Цвет')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('delivery', models.IntegerField(default=0, verbose_name='Доставка')),
                ('is_out_of_stocks', models.BooleanField(default=True, verbose_name='Есть ли в наличии')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Laptop',
                'verbose_name_plural': 'Laptops',
                'db_table': 'Laptop',
                'ordering': ['id'],
            },
        ),
    ]
